[test]
timeout = 30000
bail = false
coverage = true
include = ["**/*.test.ts", "**/tests/**/*.ts"]
exclude = ["node_modules/**", "out/**", "**/*.d.ts"]
env = { NODE_ENV = "test", LOG_LEVEL = "error" }